# -*- coding: utf-8 -*-
"""hw10_anomaly_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12D52GgTwb4k75mRCSM_y8ykqHvqk_gOJ

# **Homework 10 - Anomaly Detection**

若有任何問題，歡迎來信至助教信箱 ntu-ml-2020spring-ta@googlegroups.com

# Load and preprocess data
"""

# !gdown --id '1_zT3JOpvXFGr7mkxs3XJDeGxTn_8pItq' --output train.npy
# !gdown --id '11Y_6JDjlhIY-M5-jW1rLRshDMqeKi9Kr' --output test.npy

from torch.utils.data import (DataLoader, RandomSampler, SequentialSampler,
                              TensorDataset)
from torch.optim import Adam, AdamW
from torch.utils.data import DataLoader
from torch.autograd import Variable
import torch.nn.functional as F
from torch import nn
import torch
from sklearn.decomposition import PCA
from scipy.cluster.vq import vq, kmeans
from sklearn.metrics import f1_score, pairwise_distances, roc_auc_score
from sklearn.cluster import MiniBatchKMeans
import numpy as np
import sys
import pandas as pd
import os
import matplotlib.pyplot as plt
torch.manual_seed(0)
np.random.seed(0)
# npy檔案就是紀錄矩陣的檔案
test = np.load(sys.argv[1], allow_pickle=True)
print("Size of Testing Data:{}".format(len(test)))
# if not os.path.isdir('./result/question1'):
#         os.makedirs('./result/question1')
"""# Task

這份作業要執行的 task 是 semi-supervised anomaly detection，也就是說 training set 是乾淨的，testing 的時候才會混進 outlier data (anomaly)。
我們以某個簡單的 image dataset（image 加上他們的 label（分類））作為示範，training data 為原先 training set 中的某幾類，而 testing data 則是原先 testing set 的所有 data，要偵測的 anomaly 為 training data 中未出現的類別。label 的部分，1 為 outlier data，而 0 為 inlier data（相對於 outlier）。正確率以 AUC 計算。

方法以下列舉 3 種： KNN, PCA, Autoencoder。
"""

task = 'ae'

"""# KNN

K-Nearest-Neighbor(KNN): 假設 training data 的 label 種類不多（e.g., < 20），然而因其為未知，可以猜測其為 n，亦即假設 training data 有 n 群。先用 K-means 計算 training data 中的 n 個 centroid，再用這 n 個 centroid 對 training data 分群。應該可以觀察到，inlier data 與所分到群的 centroid 的距離應較 outlier 的此距離來得小。
"""



"""# Autoencoder

# Models & loss

課程影片參見：https://www.youtube.com/watch?v=6W8FqUGYyDo&list=PLJV_el3uVTsOK_ZK5L0Iv_EQoL1JefRL4&index=8

fcn_autoencoder and vae are from https://github.com/L1aoXingyu/pytorch-beginner
VAE 就是variational auto encoder
conv_autoencoder is from https://github.com/jellycsc/PyTorch-CIFAR-10-autoencoder/

同學們可以嘗試各種不同的 VAE 架構
"""


class fcn_autoencoder(nn.Module):
    # fully connected network
    def __init__(self):
        super(fcn_autoencoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(32 * 32 * 3, 128),
            nn.ReLU(True),
            # nn.Linear(128*12, 128),
            # nn.ReLU(True),
            nn.Linear(128, 64),
            nn.ReLU(True),
            nn.Linear(64, 12),
            nn.ReLU(True),
            nn.Linear(12, 3))
        # 用encoder降維到3維
        self.decoder = nn.Sequential(
            nn.Linear(3, 12),
            nn.ReLU(True),
            nn.Linear(12, 64),
            nn.ReLU(True),
            nn.Linear(64, 128),
            nn.ReLU(True), 
            # nn.Linear(128, 128*12),
            # nn.ReLU(True), 
            nn.Linear(128, 32 * 32 * 3),
             nn.Tanh())

    def forward(self, x):
        x1 = self.encoder(x)
        x2 = self.decoder(x1)
        return x2


class conv_autoencoder(nn.Module):
    def __init__(self):
        super(conv_autoencoder, self).__init__()
        # torch.nn.Conv2d(in_channels, out_channels, kernel_size)
        self.encoder = nn.Sequential(
            # [batch, 12, 16, 16]
            nn.Conv2d(3, 12, 4, stride=2, padding=1),
            nn.ReLU(),
            # [batch, 24, 8, 8]
            nn.Conv2d(12, 24, 4, stride=2, padding=1),
            nn.ReLU(),
			      # [batch, 48, 4, 4]
			      nn.Conv2d(24, 48, 4, stride=2, padding=1),
            nn.ReLU(),
    # 			nn.Conv2d(48, 96, 4, stride=2, padding=1),           # [batch, 96, 2, 2]
    #       nn.ReLU(),
        )
        # ConvTranspose2d就是跟Conv2d座完全相反的事情 他的stride不會是filter真正的stride 而是Conv2d的stride
        self.decoder = nn.Sequential(
#             nn.ConvTranspose2d(96, 48, 4, stride=2, padding=1),  # [batch, 48, 4, 4]
#             nn.ReLU(),
			      # [batch, 24, 8, 8]
			      nn.ConvTranspose2d(48, 24, 4, stride=2, padding=1),
            nn.ReLU(),
			      # [batch, 12, 16, 16]
			      nn.ConvTranspose2d(24, 12, 4, stride=2, padding=1),
            nn.ReLU(),
            # [batch, 3, 32, 32]
            nn.ConvTranspose2d(12, 3, 4, stride=2, padding=1),
            nn.Tanh(),
        )

    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x


class VAE(nn.Module):
    def __init__(self):
        super(VAE, self).__init__()

        self.fc1 = nn.Linear(32*32*3, 400)
        self.fc21 = nn.Linear(400, 20)
        self.fc22 = nn.Linear(400, 20)
        self.fc3 = nn.Linear(20, 400)
        self.fc4 = nn.Linear(400, 32*32*3)

    def encode(self, x):
        h1 = F.relu(self.fc1(x))
        return self.fc21(h1), self.fc22(h1)

    def reparametrize(self, mu, logvar):
        std = logvar.mul(0.5).exp_()
        if torch.cuda.is_available():
            # 產生normal distribution
            eps = torch.cuda.FloatTensor(std.size()).normal_()
        else:
            eps = torch.FloatTensor(std.size()).normal_()
        eps = Variable(eps)
        # 將encoder其中一個output做exponential後乘上 normal distribution 再來加上第一個output
        return eps.mul(std).add_(mu)

    def decode(self, z):
        h3 = F.relu(self.fc3(z))
        return F.sigmoid(self.fc4(h3))

    def forward(self, x):
        # 先讓encoder丟出兩組output
        mu, logvar = self.encode(x)
        z = self.reparametrize(mu, logvar)
        return self.decode(z), mu, logvar


def loss_vae(recon_x, x, mu, logvar, criterion):
    """
    recon_x: generating images
    x: origin images
    mu: latent mean
    logvar: latent log variance
    """
    mse = criterion(recon_x, x)  # mse loss
    # loss = 0.5 * sum(1 + log(sigma^2) - mu^2 - sigma^2)
    KLD_element = mu.pow(2).add_(logvar.exp()).mul_(-1).add_(1).add_(logvar)
    KLD = torch.sum(KLD_element).mul_(-0.5)
    # KL divergence
    return mse + KLD


"""# Training"""

import time
if task == 'ae':
    # Auto Encoder
    num_epochs = 1000
    batch_size = 128
    learning_rate = 1e-3

    # {'fcn', 'cnn', 'vae'}
    model_type = 'fcn'

    model_classes = {'fcn': fcn_autoencoder(
    ), 'cnn': conv_autoencoder(), 'vae': VAE()}
    model = model_classes[model_type].cuda()
    criterion=nn.MSELoss()
    optimizer=torch.optim.AdamW(
        model.parameters(), lr=learning_rate)
    
"""# Evaluation

將 testing 的圖片輸入 model 後，可以得到其重建的圖片，並對兩者取平方差。可以發現 inlier 的平方差應該與 outlier 的平方差形成差距明顯的兩群數據。
"""
import os
import matplotlib.pyplot as plt
def normalize(reconstructed, test):
    # normalize the image to [0,1]
    max = np.max(reconstructed.reshape(len(reconstructed),-1),axis=1)
    min = np.min(reconstructed.reshape(len(reconstructed),-1),axis=1)
    reconstructed = (reconstructed - min[:,None,None,None])/(max[:,None,None,None]-min[:,None,None,None])

    max = np.max(test.reshape(len(test),-1),axis=1)
    min = np.min(test.reshape(len(test),-1),axis=1)
    test = (test - min[:,None,None,None])/(max[:,None,None,None]-min[:,None,None,None])
    # print(test<=1)
    return reconstructed, test
    
# 其實跟train差不多
if task == 'ae':
    if model_type == 'fcn' or model_type == 'vae':
        
        y=test.reshape(len(test), -1)
    else:
        y=test

    data=torch.tensor(y, dtype=torch.float)
    test_dataset=TensorDataset(data)
    test_sampler=SequentialSampler(test_dataset)
    test_dataloader=DataLoader(
        test_dataset, sampler=test_sampler, batch_size=batch_size)

    model=torch.load(sys.argv[2], map_location='cuda')
    print("Auto-Encoder Model Type:{}".format(model_type))
    print("Total parameters:{}".format(sum(p.numel()
          for p in model.parameters())))
    print("Trainable parameters:{}".format(sum(p.numel() for p in model.parameters() if p.requires_grad)))

    model.eval()
    reconstructed=list()
    x = []

    for i, data in enumerate(test_dataloader):
        # data(1, batch size, 32 , 32, 3)
        if model_type == 'cnn':
            img=data[0].transpose(3, 1).cuda()
        else:
            img=data[0].cuda()
        # input丟進model後會經過降維並reconstruct
        output=model(img)
        if model_type == 'cnn':
            output=output.transpose(3, 1)
        elif model_type == 'vae':
            output=output[0]
        reconstructed.append(output.cpu().detach().numpy())
        # print(output.shape)
    
    reconstructed=np.concatenate(reconstructed, axis=0)
    
    
    dist = np.mean(np.square(reconstructed - y).reshape(len(y), -1), axis=1)
    y_pred = dist
    MSE_index=y_pred.argsort()
   
    

    # Draw the image with largest MSE
    print("The {}-th image has the largest MSE {:^.3f}".format(
        MSE_index[-1], y_pred[MSE_index[-1]]))

    print("The {}-th image has the smallest MSE {:^.6f}".format(
        MSE_index[0], y_pred[MSE_index[0]]))

    with open(sys.argv[3], 'w') as f:
        f.write('id,anomaly\n')
        for i in range(len(y_pred)):
            f.write('{},{}\n'.format(i+1, y_pred[i]))

